{
 "title": "YuniKorn Scheduling Analytics",
 "tags": [
  "yunikorn",
  "scheduler",
  "analytics-v1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values(yunikorn_queue_info_value{partition=\"default\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Partition Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(yunikorn_queue_running_apps_value{partition=\"default\",queue=~\"$queue\"})"
    }
   ]
  },
  {
   "title": "Completed Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(yunikorn_completed_app_info_value{partition=\"default\",queue=~\"$queue\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_total_nodes_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_total_containers_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_utilization_memory_percent_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_utilization_cpu_percent_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Pods Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_utilization_pods_percent_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_capacity_memory_bytes_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_used_memory_bytes_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_capacity_cpu_millicores_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_used_cpu_millicores_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Pods Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_capacity_pods_value{partition=\"default\"}"
    }
   ]
  },
  {
   "title": "Pods Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_partition_used_pods_value{partition=\"default\"}"
    }
   ]
  },
  { "title": "Queue Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Active Apps By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "yunikorn_queue_running_apps_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Completed Apps By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count by (queue) (yunikorn_completed_app_info_value{partition=\"default\",queue=~\"$queue\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Allocated Memory By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "yunikorn_queue_allocated_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Allocated CPU By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yunikorn_queue_allocated_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Lifecycle Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Average Scheduling Wait of Visible Completed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((((yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6) - yunikorn_completed_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))"
    }
   ]
  },
  {
   "title": "Average Accepted To Completed of Visible Completed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((yunikorn_completed_app_completed_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - yunikorn_completed_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))"
    }
   ]
  },
  {
   "title": "Average Runtime of Visible Completed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((yunikorn_completed_app_finished_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - (yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6)) / 1e9))"
    }
   ]
  },
  {
   "title": "Average Submission To Completion of Visible Completed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((yunikorn_completed_app_finished_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - yunikorn_completed_app_submission_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))"
    }
   ]
  },
  {
   "title": "Completed App Scheduling Wait Trend By Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (queue) ((((yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6) - yunikorn_completed_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Completed App Runtime Trend By Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (queue) (((yunikorn_completed_app_finished_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - (yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6)) / 1e9))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Completed App Scheduling Wait By Application",
   "type": "bargauge",
   "description": "Per-application scheduling wait for visible completed applications.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (application_id, queue) ((((yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6) - yunikorn_completed_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  {
   "title": "Completed App Accepted To Completed By Application",
   "type": "bargauge",
   "description": "Per-application accepted-to-completed duration for visible completed applications.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (application_id, queue) (((yunikorn_completed_app_completed_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - yunikorn_completed_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  {
   "title": "Completed App Runtime By Application",
   "type": "bargauge",
   "description": "Per-application runtime for visible completed applications.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (application_id, queue) (((yunikorn_completed_app_finished_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - (yunikorn_completed_app_start_timestamp_milliseconds_value{partition=\"default\",queue=~\"$queue\"} * 1e6)) / 1e9))",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  {
   "title": "Completed App Submission To Completion By Application",
   "type": "bargauge",
   "description": "Per-application end-to-end submission-to-completion duration for visible completed applications.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (application_id, queue) (((yunikorn_completed_app_finished_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - yunikorn_completed_app_submission_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9))",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  { "title": "Active App Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Active App Used Memory By Application",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "yunikorn_app_used_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  {
   "title": "Active App Used CPU By Application",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yunikorn_app_used_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  {
   "title": "Current Active App Scheduling Delay By Application",
   "type": "bargauge",
   "description": "Current scheduling delay from Accepted to Running for active applications in the visible queue scope.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(yunikorn_app_running_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"} - yunikorn_app_accepted_timestamp_nanoseconds_value{partition=\"default\",queue=~\"$queue\"}) / 1e9",
     "legendFormat": "{{queue}} / {{application_id}}"
    }
   ]
  },
  { "title": "Queue Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Pending Memory By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "yunikorn_queue_pending_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Pending CPU By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yunikorn_queue_pending_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Guaranteed Memory By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "yunikorn_queue_guaranteed_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Guaranteed CPU By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yunikorn_queue_guaranteed_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Abs Used Memory Capacity By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "yunikorn_queue_abs_used_capacity_memory_percent_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Abs Used CPU Capacity By Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "yunikorn_queue_abs_used_capacity_cpu_percent_value{partition=\"default\",queue=~\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Queue Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Selected Queue Pending Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_pending_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Pending CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_pending_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Pending Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_pending_pods_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Current Priority",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(yunikorn_queue_current_priority_value{partition=\"default\",queue=~\"$queue\"}, 0)"
    }
   ]
  },
  {
   "title": "Selected Queue Guaranteed Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_guaranteed_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Guaranteed CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_guaranteed_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Max Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_max_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Max CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_max_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  { "title": "Queue Headroom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Selected Queue Headroom Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_headroom_memory_bytes_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Headroom CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_headroom_cpu_millicores_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "Selected Queue Preemption Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yunikorn_queue_preemption_enabled_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  },
  { "title": "Queue Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Queue Metadata",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "yunikorn_queue_info_value{partition=\"default\",queue=~\"$queue\"}"
    }
   ]
  }
 ]
}